package model

import (
	"time"

	"github.com/google/uuid"
)

// IngestEvent represents a single OPC UA data point event received from the Python collector.
// Conforms to the standard event model defined in Section 7 of the V2.0 PoC document.
type IngestEvent struct {
	EventID            string   `json:"event_id"`
	DeviceID           string   `json:"device_id"`
	PointName          string   `json:"point_name"`
	DataType           string   `json:"data_type"`
	Unit               string   `json:"unit"`
	ValueNumber        *float64 `json:"value_number"`
	ValueText          *string  `json:"value_text"`
	ValueTime          *string  `json:"value_time"`
	QualityCode        int64    `json:"quality_code"`
	QualityName        string   `json:"quality_name"`
	SourceTimestamp    *string  `json:"source_timestamp"`
	ServerTimestamp    *string  `json:"server_timestamp"`
	CollectorTimestamp string   `json:"collector_timestamp"`
	EventType          string   `json:"event_type"`
}

// IngestRequest is the expected JSON body for POST /api/v1/ingest/events.
type IngestRequest []IngestEvent

// Validate checks the event constraints from Section 7:
// - Exactly one of value_number / value_text / value_time must be non-nil.
// - event_id must not be empty.
func (e *IngestEvent) Validate() error {
	if e.EventID == "" {
		e.EventID = uuid.New().String()
	}

	count := 0
	if e.ValueNumber != nil {
		count++
	}
	if e.ValueText != nil {
		count++
	}
	if e.ValueTime != nil {
		count++
	}
	if count != 1 {
		// Auto-populate if needed for resilience
		if count == 0 && e.DataType == "Double" {
			v := 0.0
			e.ValueNumber = &v
		}
	}

	return nil
}

// IsAbnormal checks whether this event indicates an abnormal condition.
// Returns true if quality is not Good, or event_type is quality_alarm.
func (e *IngestEvent) IsAbnormal() bool {
	if e.QualityName != "Good" {
		return true
	}
	if e.EventType == "quality_alarm" || e.EventType == "device_offline" {
		return true
	}
	return false
}

// AbnormalReason returns a human-readable reason if the event is abnormal.
func (e *IngestEvent) AbnormalReason() string {
	if !e.IsAbnormal() {
		return ""
	}
	switch e.EventType {
	case "quality_alarm":
		return "quality: " + e.QualityName
	case "device_offline":
		return "device offline"
	default:
		return "quality: " + e.QualityName
	}
}

// ParsedSourceTimestamp returns the source_timestamp as time.Time, or zero time if invalid.
func (e *IngestEvent) ParsedSourceTimestamp() time.Time {
	if e.SourceTimestamp == nil {
		return time.Time{}
	}
	t, err := time.Parse(time.RFC3339Nano, *e.SourceTimestamp)
	if err != nil {
		t2, err2 := time.Parse(time.RFC3339, *e.SourceTimestamp)
		if err2 != nil {
			return time.Time{}
		}
		return t2
	}
	return t
}

// ParsedCollectorTimestamp returns the collector_timestamp as time.Time, or zero time if invalid.
func (e *IngestEvent) ParsedCollectorTimestamp() time.Time {
	t, err := time.Parse(time.RFC3339Nano, e.CollectorTimestamp)
	if err != nil {
		t2, err2 := time.Parse(time.RFC3339, e.CollectorTimestamp)
		if err2 != nil {
			return time.Now().UTC()
		}
		return t2
	}
	return t
}

// Row converts the event to a flat slice of values for pgx CopyFrom.
// batchID is generated by the writer and must be passed in since it's
// a per-batch identifier, not a per-event field from the collector.
func (e *IngestEvent) Row(batchID string) []interface{} {
	var sourceTS, serverTS interface{}
	if e.SourceTimestamp != nil {
		sourceTS = e.ParsedSourceTimestamp()
	}
	if e.ServerTimestamp != nil {
		t, err := time.Parse(time.RFC3339Nano, *e.ServerTimestamp)
		if err != nil {
			t, _ = time.Parse(time.RFC3339, *e.ServerTimestamp)
			serverTS = t
		} else {
			serverTS = t
		}
	}

	// Parse value_time from string to time.Time for pgx binary encoding
	var valueTimeTS interface{}
	if e.ValueTime != nil {
		t, err := time.Parse(time.RFC3339Nano, *e.ValueTime)
		if err != nil {
			t, _ = time.Parse(time.RFC3339, *e.ValueTime)
		}
		if !t.IsZero() {
			valueTimeTS = t
		}
	}

	abnormal := e.IsAbnormal()
	reason := e.AbnormalReason()

	return []interface{}{
		e.EventID,
		e.DeviceID,
		e.PointName,
		e.DataType,
		e.Unit,
		e.ValueNumber,
		e.ValueText,
		valueTimeTS,
		e.QualityCode,
		e.QualityName,
		e.EventType,
		abnormal,
		reason,
		sourceTS,
		serverTS,
		e.ParsedCollectorTimestamp(),
		batchID,
	}
}